### ISSUE TITLE
이메일 인증, 회원 가입 구현

### ISSUE THREAD

**Issue by signature-hyeon** [effective-tech-interview/effective-tech-interview-be#1]
## Feature Description
- 이메일 인증, 회원 가입

## Todo list

- [x] 이메일 인증 코드 전송
- [x] 이메일 인증 코드 확인
- [x] 회원 가입
- [x] 닉네임 랜덤 생성
